#!/usr/bin/env python

from gradelib import *

r = Runner(save("xv6.out"))


@test(20, "seccomp test")
def test_seccomp_test():
    r.run_qemu(shell_script([
        'seccomptest'
    ]), make_args=["CPUS=1", "LAB_SYSCALL_TEST=on"])
    r.match("seccomp test OK")


run_tests(exit_on_failure=False)
